package avuuna.player.gui;

import avuuna.player.logic.*;
import avuuna.player.utils.*;
import javax.swing.*;
import javazoom.jl.player.basic.*;

/**
 *
 * @author pegasusmax
 */
public class PlaylistPanel extends JPanel implements Observador {

    private static final String ACTUAL = "> ";
    private final Player player;
    private final DefaultListModel<String> listModel;

    public PlaylistPanel(Player player) {
        this.listModel = new DefaultListModel();
        this.player = player;
        initComponents();
    }

    @Override
    public void update() {
        listModel.clear();
        for (Song song : player.getSongs()) {
            String resp = song.getName();
            if (player.getActual() != null && player.getActual().equals(song)) {
                resp = ACTUAL + resp;
            }
            listModel.addElement(resp);
        }
    }

    private void clearPlaylist() {
        try {
            player.clearList();
        } catch (BasicPlayerException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error found while clearing the playlist", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void openSong(String selected) {
        try {
            Song song = player.getSong(selected);
            player.setActual(song);
            player.stop();
            player.open(song);
        } catch (BasicPlayerException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error found while opening song", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        songList = new javax.swing.JList();
        clearButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Playlist Panel"));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(260, 23));

        songList.setModel(listModel);
        songList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        songList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                songListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(songList);

        clearButton.setText("Clear list");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(clearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton))
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearPlaylist();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void songListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_songListMouseClicked
        if (evt.getClickCount() == 2) {
            String selected = (String) songList.getSelectedValue();
            if (!selected.contains(ACTUAL)) {
                openSong(selected);
            }
        }
    }//GEN-LAST:event_songListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList songList;
    // End of variables declaration//GEN-END:variables
}
